/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cbrc;

import java.awt.Color;

/**
 *
 * @author DELL
 */
public class entervalidpath extends javax.swing.JFrame {

    /**
     * Creates new form entervalidpath
     */
    public entervalidpath() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ep = new javax.swing.JPanel();
        el = new javax.swing.JLabel();
        mp = new javax.swing.JPanel();
        ml = new javax.swing.JLabel();
        op = new javax.swing.JPanel();
        ol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ep.setBackground(new java.awt.Color(255, 255, 255));
        ep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        el.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        el.setForeground(new java.awt.Color(0, 153, 255));
        el.setText("                ERROR!");

        javax.swing.GroupLayout epLayout = new javax.swing.GroupLayout(ep);
        ep.setLayout(epLayout);
        epLayout.setHorizontalGroup(
            epLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(el, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        epLayout.setVerticalGroup(
            epLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(el, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        ep.setBounds(0, 0, 400, 50);
        jLayeredPane1.add(ep, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mp.setBackground(new java.awt.Color(0, 153, 255));
        mp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ml.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ml.setForeground(new java.awt.Color(255, 255, 255));
        ml.setText("Please enter a valid directory sub-path to continue");

        op.setBackground(new java.awt.Color(0, 153, 255));

        ol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ol.setForeground(new java.awt.Color(255, 255, 255));
        ol.setText("      OK");
        ol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                olMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                olMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                olMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                olMousePressed(evt);
            }
        });

        javax.swing.GroupLayout opLayout = new javax.swing.GroupLayout(op);
        op.setLayout(opLayout);
        opLayout.setHorizontalGroup(
            opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(ol, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        opLayout.setVerticalGroup(
            opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(ol, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout mpLayout = new javax.swing.GroupLayout(mp);
        mp.setLayout(mpLayout);
        mpLayout.setHorizontalGroup(
            mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mpLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ml, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        mpLayout.setVerticalGroup(
            mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ml, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        mp.setBounds(0, 50, 400, 110);
        jLayeredPane1.add(mp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-161)/2, 400, 161);
    }// </editor-fold>//GEN-END:initComponents

    private void olMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_olMouseClicked
Color mag=new Color(0,153,255);
    private void olMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olMouseEntered
      op.setBackground(Color.WHITE);
      ol.setForeground(mag);// TODO add your handling code here:
    }//GEN-LAST:event_olMouseEntered

    private void olMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olMouseExited
        op.setBackground(mag);
      ol.setForeground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_olMouseExited

    private void olMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olMousePressed
      dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_olMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entervalidpath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entervalidpath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entervalidpath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entervalidpath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entervalidpath().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel el;
    private javax.swing.JPanel ep;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel ml;
    private javax.swing.JPanel mp;
    private javax.swing.JLabel ol;
    private javax.swing.JPanel op;
    // End of variables declaration//GEN-END:variables
}
