/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cbrc;

import AppPackage.AnimationClass;
import java.awt.Color;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ThreadFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author DELL
 * refer:https://www.youtube.com/watch?v=CIPNM6PXm58 <the author>
 */
public class Slideshow extends javax.swing.JFrame {
AnimationClass AC=new AnimationClass();
  confirmexit bb=new confirmexit();  /**
     * Creates new form Slideshow
     */
    public Slideshow() {
        initComponents();
        SlideShow();
    }
public void SlideShow(){

 Thread t=new Thread(){
   
       int count=0;
        public void run(){
            

      try{
      
      while(true){
      
          switch(count){
          
              case 0:
                  ImageIcon II=new ImageIcon(getClass().getResource("/samples/4.jpg"));
                  bg1.setIcon(II);
                  Thread.sleep(3000);
                  AC.jLabelXLeft(0,-755,30,5,bg1);//replace with 70 to create a graphic effect like files are being deleted as in xp.
                                                   //so replace images with 'file google img' jpg
                  
                  AC.jLabelXLeft(755,0,30,5,bg2);
                  count=1;
                  break;
                  
               case 1:
                  ImageIcon II1=new ImageIcon(getClass().getResource("/samples/5.jpg"));
                  bg2.setIcon(II1);
                  Thread.sleep(3000);
                  AC.jLabelXRight(-755,0,30,5,bg1);
                  AC.jLabelXRight(0,755,30,5,bg2);

                  
                  count=2;
                  break;   
               
               case 2:
                   ImageIcon II2=new ImageIcon(getClass().getResource("/samples/pdddf.png"));
                  bg1.setIcon(II2);
                  Thread.sleep(3000);
                  AC.jLabelXLeft(0,-755,30,5,bg1);
                  AC.jLabelXLeft(755,0,30,5,bg2);
                              

                  count=3;
                  break;   
                   
                case 3:
                      ImageIcon II3=new ImageIcon(getClass().getResource("/samples/4.jpg"));
                  bg2.setIcon(II3);
                  Thread.sleep(3000);
                  AC.jLabelXRight(-755,0,30,5,bg1);
                  AC.jLabelXRight(0,755,30,5,bg2);
                              

                  count=0;
                  break;    
               }
      }
      
      
      }
      
      
      catch(Exception e){};




   }





   };

   t.start();




}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        skiptutorialpanel = new javax.swing.JPanel();
        ll1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        exitpanel = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        bg4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(755, 510));
        setUndecorated(true);

        skiptutorialpanel.setBackground(new java.awt.Color(204, 0, 51));
        skiptutorialpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ll1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ll1.setForeground(new java.awt.Color(255, 255, 255));
        ll1.setText("SKIP TUTORIAL");
        ll1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ll1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ll1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ll1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout skiptutorialpanelLayout = new javax.swing.GroupLayout(skiptutorialpanel);
        skiptutorialpanel.setLayout(skiptutorialpanelLayout);
        skiptutorialpanelLayout.setHorizontalGroup(
            skiptutorialpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, skiptutorialpanelLayout.createSequentialGroup()
                .addContainerGap(620, Short.MAX_VALUE)
                .addGroup(skiptutorialpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ll1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        skiptutorialpanelLayout.setVerticalGroup(
            skiptutorialpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skiptutorialpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ll1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        skiptutorialpanel.setBounds(0, 450, 755, 60);
        jLayeredPane2.add(skiptutorialpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        exitpanel.setBackground(new java.awt.Color(204, 0, 51));
        exitpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout exitpanelLayout = new javax.swing.GroupLayout(exitpanel);
        exitpanel.setLayout(exitpanelLayout);
        exitpanelLayout.setHorizontalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitpanelLayout.createSequentialGroup()
                .addContainerGap(718, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        exitpanelLayout.setVerticalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exitpanel.setBounds(0, 0, 755, 60);
        jLayeredPane2.add(exitpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bg1.setBackground(new java.awt.Color(255, 255, 255));
        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/samples/sample1.PNG"))); // NOI18N
        bg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bg1.setPreferredSize(new java.awt.Dimension(755, 390));
        bg1.setBounds(0, 60, 755, 390);
        jLayeredPane2.add(bg1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/samples/sample2.PNG"))); // NOI18N
        bg2.setText("jLabel1");
        bg2.setPreferredSize(new java.awt.Dimension(755, 390));
        bg2.setBounds(755, 60, 755, 390);
        jLayeredPane2.add(bg2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/samples/sample3.PNG"))); // NOI18N
        bg3.setPreferredSize(new java.awt.Dimension(755, 390));
        bg3.setBounds(1510, 60, 755, 390);
        jLayeredPane2.add(bg3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/samples/sample4.PNG"))); // NOI18N
        bg4.setPreferredSize(new java.awt.Dimension(755, 300));
        bg4.setBounds(2265, 60, 755, 300);
        jLayeredPane2.add(bg4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-755)/2, (screenSize.height-510)/2, 755, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
bb.setVisible(true);        
       
          
  // TODO add your handling code here:
    }//GEN-LAST:event_exitMousePressed

    private void ll1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ll1MouseEntered
ll1.setForeground(Color.YELLOW);        // TODO add your handling code here:
    }//GEN-LAST:event_ll1MouseEntered

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
exit.setForeground(Color.RED);          // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
      exit.setForeground(Color.WHITE);  // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseExited

    private void ll1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ll1MouseExited
ll1.setForeground(Color.WHITE);          // TODO add your handling code here:
    }//GEN-LAST:event_ll1MouseExited

    private void ll1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ll1MousePressed
        venom wrk=new venom();
        this.dispose();
        wrk.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ll1MousePressed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Slideshow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Slideshow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Slideshow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Slideshow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Slideshow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JLabel bg4;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel exitpanel;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel ll1;
    private javax.swing.JPanel skiptutorialpanel;
    // End of variables declaration//GEN-END:variables
}
